initialization
setUp
	calendar := HebrewCalendar.
	nisan := calendar nisan.
	iyyar := calendar iyyar.
	sivan := calendar sivan.
	tammuz := calendar tammuz.
	av := calendar av.
	elul := calendar elul.
	tishri := calendar tishri.
	marheshvan := calendar marheshvan.
	kislev := calendar kislev.
	tevet := calendar tevet.
	shevat := calendar shevat.
	adar := calendar adar.
	adarI := calendar adarI.
	adarII := calendar adarII.
	zeroMonths := 0 monthsMeasure.
	oneMonth := 1 monthMeasure.
	twoMonths := 2 monthsMeasure.
	elevenMonths := 11 monthsMeasure.
	twelveMonths := 12 monthsMeasure