test comparing
testEqual

	self assert: nisan = nisan.
	self assert: iyyar = iyyar.
	self assert: sivan = sivan.
	self assert: tammuz = tammuz.
	self assert: av = av.
	self assert: elul = elul.
	self assert: tishri = tishri.
	self assert: marheshvan = marheshvan.
	self assert: kislev = kislev.
	self assert: tevet = tevet.
	self assert: shevat = shevat.
	self assert: adarI = adarI.
	self assert: adarII = adarII