test accessing
testFirstDayOfMonth

	self assert: nisan firstDayOfMonth = Nisan first.
	self assert: iyyar firstDayOfMonth = Iyyar first.
	self assert: sivan firstDayOfMonth = Sivan first.
	self assert: tammuz firstDayOfMonth = Tammuz first.
	self assert: av firstDayOfMonth = Av first.
	self assert: elul firstDayOfMonth = Elul first.
	self assert: tishri firstDayOfMonth = Tishri first.
	self assert: marheshvan firstDayOfMonth = Marheshvan first.
	self assert: kislev firstDayOfMonth = Kislev first.
	self assert: tevet firstDayOfMonth = Tevet first.
	self assert: shevat firstDayOfMonth = Shevat first.
	self assert: adarI firstDayOfMonth = AdarI first.
	self assert: adarII firstDayOfMonth = AdarII first