test day of month creation
testDayOfMonthCreation

	self assert: kislev first = (DayOfMonth monthNumber: 9 dayNumber: 1 calendar: calendar).
	self assert: kislev second = (DayOfMonth monthNumber: 9 dayNumber: 2 calendar: calendar).
	self assert: kislev third = (DayOfMonth monthNumber: 9 dayNumber: 3 calendar: calendar).
	self assert: kislev fourth = (DayOfMonth monthNumber: 9 dayNumber: 4 calendar: calendar).
	self assert: kislev fifth = (DayOfMonth monthNumber: 9 dayNumber: 5 calendar: calendar).
	self assert: kislev sixth = (DayOfMonth monthNumber: 9 dayNumber: 6 calendar: calendar).
	self assert: kislev seventh = (DayOfMonth monthNumber: 9 dayNumber: 7 calendar: calendar).
	self assert: kislev eighth = (DayOfMonth monthNumber: 9 dayNumber: 8 calendar: calendar).
	self assert: kislev ninth = (DayOfMonth monthNumber: 9 dayNumber: 9 calendar: calendar).
	self assert: kislev tenth = (DayOfMonth monthNumber: 9 dayNumber: 10 calendar: calendar).
	self assert: kislev eleventh = (DayOfMonth monthNumber: 9 dayNumber: 11 calendar: calendar).
	self assert: kislev twelfth = (DayOfMonth monthNumber: 9 dayNumber: 12 calendar: calendar).
	self assert: kislev thirteenth = (DayOfMonth monthNumber: 9 dayNumber: 13 calendar: calendar).
	self assert: kislev fourteenth = (DayOfMonth monthNumber: 9 dayNumber: 14 calendar: calendar).
	self assert: kislev fifteenth = (DayOfMonth monthNumber: 9 dayNumber: 15 calendar: calendar).
	self assert: kislev sixteenth = (DayOfMonth monthNumber: 9 dayNumber: 16 calendar: calendar).
	self assert: kislev seventeenth = (DayOfMonth monthNumber: 9 dayNumber: 17 calendar: calendar).
	self assert: kislev eighteenth = (DayOfMonth monthNumber: 9 dayNumber: 18 calendar: calendar).
	self assert: kislev nineteenth = (DayOfMonth monthNumber: 9 dayNumber: 19 calendar: calendar).
	self assert: kislev twentieth = (DayOfMonth monthNumber: 9 dayNumber: 20 calendar: calendar).
	self assert: kislev twentyfirst = (DayOfMonth monthNumber: 9 dayNumber: 21 calendar: calendar).
	self assert: kislev twentysecond = (DayOfMonth monthNumber: 9 dayNumber: 22 calendar: calendar).
	self assert: kislev twentythird = (DayOfMonth monthNumber: 9 dayNumber: 23 calendar: calendar).
	self assert: kislev twentyfourth = (DayOfMonth monthNumber: 9 dayNumber: 24 calendar: calendar).
	self assert: kislev twentyfifth = (DayOfMonth monthNumber: 9 dayNumber: 25 calendar: calendar).
	self assert: kislev twentysixth = (DayOfMonth monthNumber: 9 dayNumber: 26 calendar: calendar).
	self assert: kislev twentyseventh = (DayOfMonth monthNumber: 9 dayNumber: 27 calendar: calendar).
	self assert: kislev twentyeighth = (DayOfMonth monthNumber: 9 dayNumber: 28 calendar: calendar).
	self assert: kislev twentyninth = (DayOfMonth monthNumber: 9 dayNumber: 29 calendar: calendar).
	self assert: kislev thirtieth = (DayOfMonth monthNumber: 9 dayNumber: 30 calendar: calendar)