test accessing
testLastDayOfMonth

	self assert: nisan lastDayOfMonth = Nisan thirtieth.
	self assert: iyyar lastDayOfMonth = Iyyar twentyninth.
	self assert: sivan lastDayOfMonth = Sivan thirtieth.
	self assert: tammuz lastDayOfMonth = Tammuz twentyninth.
	self assert: av lastDayOfMonth = Av thirtieth.
	self assert: elul lastDayOfMonth = Elul twentyninth.
	self assert: tishri lastDayOfMonth = Tishri thirtieth.
	self assert: marheshvan lastDayOfMonth = Marheshvan thirtieth.
	self assert: kislev lastDayOfMonth = Kislev thirtieth.
	self assert: tevet lastDayOfMonth = Tevet twentyninth.
	self assert: shevat lastDayOfMonth = Shevat thirtieth.
	self assert: adarI lastDayOfMonth = AdarI thirtieth.
	self assert: adarII lastDayOfMonth = AdarII twentyninth