test accessing
testNumberOfDays
	self assert: nisan numberOfDays = 30 daysMeasure.
	self assert: iyyar numberOfDays = 29 daysMeasure.
	self assert: sivan numberOfDays = 30 daysMeasure.
	self assert: tammuz numberOfDays = 29 daysMeasure.
	self assert: av numberOfDays = 30 daysMeasure.
	self assert: elul numberOfDays = 29 daysMeasure.
	self assert: tishri numberOfDays = 30 daysMeasure.
	self assert: marheshvan numberOfDays = 30 daysMeasure.
	self assert: kislev numberOfDays = 30 daysMeasure.
	self assert: tevet numberOfDays = 29 daysMeasure.
	self assert: shevat numberOfDays = 30 daysMeasure.
	self assert: adarI numberOfDays = 30 daysMeasure.
	self assert: adarII numberOfDays = 29 daysMeasure