test accessing
testLastDayNumber

	self assert: nisan lastDayNumber = 30.
	self assert: iyyar lastDayNumber = 29.
	self assert: sivan lastDayNumber = 30.
	self assert: tammuz lastDayNumber = 29.
	self assert: av lastDayNumber = 30.
	self assert: elul lastDayNumber = 29.
	self assert: tishri lastDayNumber = 30.
	self assert: marheshvan lastDayNumber = 30.
	self assert: kislev lastDayNumber = 30.
	self assert: tevet lastDayNumber = 29.
	self assert: shevat lastDayNumber = 30.
	self assert: adarI lastDayNumber = 30.
	self assert: adarII lastDayNumber = 29