test comparing
testHash

	self assert: nisan hash = nisan hash.
	self assert: iyyar hash = iyyar hash.
	self assert: sivan hash = sivan hash.
	self assert: tammuz hash = tammuz hash.
	self assert: av hash = av hash.
	self assert: elul hash = elul hash.
	self assert: tishri hash = tishri hash.
	self assert: marheshvan hash = marheshvan hash.
	self assert: kislev hash = kislev hash.
	self assert: tevet hash = tevet hash.
	self assert: shevat hash = shevat hash.
	self assert: adarI hash = adarI hash.
	self assert: adarII hash = adarII hash