SystemOrganization addCategory: #'Chalten-Core'!
SystemOrganization addCategory: 'Chalten-Core-FilterModel'!
SystemOrganization addCategory: 'Chalten-Core-GregorianModel'!
SystemOrganization addCategory: 'Chalten-Core-HebrewModel'!
SystemOrganization addCategory: 'Chalten-Core-IslamicModel'!
SystemOrganization addCategory: 'Chalten-Core-JulianModel'!
SystemOrganization addCategory: 'Chalten-Core-RomanModel'!
SystemOrganization addCategory: 'Chalten-Core-TimeModel'!
