Extension { #name : #MonthOfYear }

{ #category : #'*Chalten-Core-HebrewModel' }
MonthOfYear class >> adarIIOf: aYear [

	^self year: aYear month: HebrewCalendar adarII
]

{ #category : #'*Chalten-Core-HebrewModel' }
MonthOfYear class >> adarIOf: aYear [

	^self year: aYear month: HebrewCalendar adarI
]

{ #category : #'*Chalten-Core-HebrewModel' }
MonthOfYear class >> adarOf: aYear [

	^self year: aYear month: HebrewCalendar adar
]

{ #category : #'*Chalten-Core-RomanModel' }
MonthOfYear class >> aprilOf: aYear [

	^self year: aYear month: aYear calendar april
]

{ #category : #'*Chalten-Core-RomanModel' }
MonthOfYear class >> augustOf: aYear [

	^self year: aYear month: aYear calendar august
]

{ #category : #'*Chalten-Core-HebrewModel' }
MonthOfYear class >> avOf: aYear [

	^self year: aYear month: HebrewCalendar av
]

{ #category : #'*Chalten-Core-RomanModel' }
MonthOfYear class >> decemberOf: aYear [

	^self year: aYear month: aYear calendar december
]

{ #category : #'*Chalten-Core-IslamicModel' }
MonthOfYear class >> dhuAlHijjaOf: aYear [

	^self year: aYear month: IslamicCalendar dhuAlHijja
]

{ #category : #'*Chalten-Core-IslamicModel' }
MonthOfYear class >> dhuAlQadaOf: aYear [

	^self year: aYear month: IslamicCalendar dhuAlQada
]

{ #category : #'*Chalten-Core-HebrewModel' }
MonthOfYear class >> elulOf: aYear [

	^self year: aYear month: HebrewCalendar elul
]

{ #category : #'*Chalten-Core-RomanModel' }
MonthOfYear class >> februaryOf: aYear [

	^self year: aYear month: aYear calendar february
]

{ #category : #'*Chalten-Core-HebrewModel' }
MonthOfYear class >> iyyarOf: aYear [

	^self year: aYear month: HebrewCalendar iyyar
]

{ #category : #'*Chalten-Core-RomanModel' }
MonthOfYear class >> januaryOf: aYear [

	^self year: aYear month: aYear calendar january
]

{ #category : #'*Chalten-Core-RomanModel' }
MonthOfYear class >> julyOf: aYear [

	^self year: aYear month: aYear calendar july
]

{ #category : #'*Chalten-Core-IslamicModel' }
MonthOfYear class >> jumadaIIOf: aYear [

	^self year: aYear month: IslamicCalendar jumadaII
]

{ #category : #'*Chalten-Core-IslamicModel' }
MonthOfYear class >> jumadaIOf: aYear [

	^self year: aYear month: IslamicCalendar jumadaI
]

{ #category : #'*Chalten-Core-RomanModel' }
MonthOfYear class >> juneOf: aYear [

	^self year: aYear month: aYear calendar june
]

{ #category : #'*Chalten-Core-HebrewModel' }
MonthOfYear class >> kislevOf: aYear [

	^self year: aYear month: HebrewCalendar kislev
]

{ #category : #'*Chalten-Core-RomanModel' }
MonthOfYear class >> marchOf: aYear [

	^self year: aYear month: aYear calendar march
]

{ #category : #'*Chalten-Core-HebrewModel' }
MonthOfYear class >> marheshvanOf: aYear [

	^self year: aYear month: HebrewCalendar marheshvan
]

{ #category : #'*Chalten-Core-RomanModel' }
MonthOfYear class >> mayOf: aYear [

	^self year: aYear month: aYear calendar may


]

{ #category : #'*Chalten-Core-IslamicModel' }
MonthOfYear class >> muharramOf: aYear [

	^self year: aYear month: IslamicCalendar muharram
]

{ #category : #'*Chalten-Core-HebrewModel' }
MonthOfYear class >> nisanOf: aYear [

	^self year: aYear month: HebrewCalendar nisan
]

{ #category : #'*Chalten-Core-RomanModel' }
MonthOfYear class >> novemberOf: aYear [

	^self year: aYear month: aYear calendar november
]

{ #category : #'*Chalten-Core-RomanModel' }
MonthOfYear class >> octoberOf: aYear [

	^self year: aYear month: aYear calendar october
]

{ #category : #'*Chalten-Core-IslamicModel' }
MonthOfYear class >> rabiIIOf: aYear [

	^self year: aYear month: IslamicCalendar rabiII
]

{ #category : #'*Chalten-Core-IslamicModel' }
MonthOfYear class >> rabiIOf: aYear [

	^self year: aYear month: IslamicCalendar rabiI
]

{ #category : #'*Chalten-Core-IslamicModel' }
MonthOfYear class >> rajabOf: aYear [

	^self year: aYear month: IslamicCalendar rajab
]

{ #category : #'*Chalten-Core-IslamicModel' }
MonthOfYear class >> ramadanOf: aYear [

	^self year: aYear month: IslamicCalendar ramadan
]

{ #category : #'*Chalten-Core-IslamicModel' }
MonthOfYear class >> safarOf: aYear [

	^self year: aYear month: IslamicCalendar safar
]

{ #category : #'*Chalten-Core-RomanModel' }
MonthOfYear class >> septemberOf: aYear [

	^self year: aYear month: aYear calendar september
]

{ #category : #'*Chalten-Core-IslamicModel' }
MonthOfYear class >> shabanOf: aYear [

	^self year: aYear month: IslamicCalendar shaban
]

{ #category : #'*Chalten-Core-IslamicModel' }
MonthOfYear class >> shawwalOf: aYear [

	^self year: aYear month: IslamicCalendar shawwal
]

{ #category : #'*Chalten-Core-HebrewModel' }
MonthOfYear class >> shevatOf: aYear [

	^self year: aYear month: HebrewCalendar shevat
]

{ #category : #'*Chalten-Core-HebrewModel' }
MonthOfYear class >> sivanOf: aYear [

	^self year: aYear month: HebrewCalendar sivan
]

{ #category : #'*Chalten-Core-HebrewModel' }
MonthOfYear class >> tammuzOf: aYear [

	^self year: aYear month: HebrewCalendar tammuz
]

{ #category : #'*Chalten-Core-HebrewModel' }
MonthOfYear class >> tevetOf: aYear [

	^self year: aYear month: HebrewCalendar tevet
]

{ #category : #'*Chalten-Core-HebrewModel' }
MonthOfYear class >> tishriOf: aYear [

	^self year: aYear month: HebrewCalendar tishri
]
