test global variables
testMonthsGlobalVariables

	self
		assert: Nisan = HebrewCalendar nisan;
		assert: Iyyar = HebrewCalendar iyyar;
		assert: Sivan = HebrewCalendar sivan;
		assert: Tammuz = HebrewCalendar tammuz;
		assert: Av = HebrewCalendar av;
		assert: Elul = HebrewCalendar elul;
		assert: Tishri = HebrewCalendar tishri;
		assert: Marheshvan = HebrewCalendar marheshvan;
		assert: Kislev = HebrewCalendar kislev;
		assert: Tevet = HebrewCalendar tevet;
		assert: Shevat = HebrewCalendar shevat;
		assert: AdarI = HebrewCalendar adarI;
		assert: AdarII = HebrewCalendar adarII;
		assert: Adar = HebrewCalendar adar