test testing months
testIsIn

	self assert: (Nisan seventh, 5767 isIn: Nisan).
	self assert: (Iyyar seventh, 5767 isIn: Iyyar).
	self assert: (Sivan seventh, 5767 isIn: Sivan).
	self assert: (Tammuz seventh, 5767 isIn: Tammuz).
	self assert: (Av seventh, 5767 isIn: Av).
	self assert: (Elul seventh, 5767 isIn: Elul).
	self assert: (Tishri seventh, 5767 isIn: Tishri).
	self assert: (Marheshvan seventh, 5767 isIn: Marheshvan).
	self assert: (Kislev seventh, 5767 isIn: Kislev).
	self assert: (Tevet seventh, 5767 isIn: Tevet).
	self assert: (Shevat seventh, 5767 isIn: Shevat).
	self assert: (Adar seventh, 5767 isIn: Adar).
	self assert: (AdarI seventh, 5768 isIn: AdarI).
	self assert: (AdarII seventh, 5768 isIn: AdarII)