test enumerating
testNext

	self assert: nisan next = iyyar.
	self assert: iyyar next = sivan.
	self assert: sivan next = tammuz.
	self assert: tammuz next = av.
	self assert: av next = elul.
	self assert: elul next = tishri.
	self assert: tishri next = marheshvan.
	self assert: marheshvan next = kislev.
	self assert: kislev next = tevet.
	self assert: tevet next = shevat.
	self assert: shevat next = adar.
	self assert: adar next = nisan