test testing
testIs

	self assert: (Nisan is: nisan).
	self assert: (Iyyar is: iyyar).
	self assert: (Sivan is: sivan).
	self assert: (Tammuz is: tammuz).
	self assert: (Av is: av).
	self assert: (Elul is: elul).
	self assert: (Tishri is: tishri).
	self assert: (Marheshvan is: marheshvan).
	self assert: (Kislev is: kislev).
	self assert: (Tevet is: tevet).
	self assert: (Shevat is: shevat).
	self assert: (Adar is: adar).
	self assert: (AdarI is: adarI).
	self assert: (AdarII is: adarII)