test printing
testPrintString

	self assert: nisan printString = 'Nisan'.
	self assert: iyyar printString = 'Iyyar'.
	self assert: sivan printString = 'Sivan'.
	self assert: tammuz printString = 'Tammuz'.
	self assert: av printString = 'Av'.
	self assert: elul printString = 'Elul'.
	self assert: tishri printString = 'Tishri'.
	self assert: marheshvan printString = 'Marheshvan'.
	self assert: kislev printString = 'Kislev'.
	self assert: tevet printString = 'Tevet'.
	self assert: shevat printString = 'Shevat'.
	self assert: adarI printString = 'Adar I'.
	self assert: adarII printString = 'Adar II'