test global variables
testMonthsGlobalVariables

	self
		assert: January = GregorianCalendar january;
		assert: February = GregorianCalendar february;
		assert: March = GregorianCalendar march;
		assert: April = GregorianCalendar april;
		assert: May = GregorianCalendar may;
		assert: June = GregorianCalendar june;
		assert: July = GregorianCalendar july;
		assert: August = GregorianCalendar august;
		assert: September = GregorianCalendar september;
		assert: October = GregorianCalendar october;
		assert: November = GregorianCalendar november;
		assert: December = GregorianCalendar december