test global variables
testMonthsGlobalVariables

	self
		assert: Muharram = IslamicCalendar muharram;
		assert: Safar = IslamicCalendar safar;
		assert: RabiI = IslamicCalendar rabiI;
		assert: RabiII = IslamicCalendar rabiII;
		assert: JumadaI = IslamicCalendar jumadaI;
		assert: JumadaII = IslamicCalendar jumadaII;
		assert: Rajab = IslamicCalendar rajab;
		assert: Shaban = IslamicCalendar shaban;
		assert: Ramadan = IslamicCalendar ramadan;
		assert: Shawwal = IslamicCalendar shawwal;
		assert: DhuAlQada = IslamicCalendar dhuAlQada;
		assert: DhuAlHijja = IslamicCalendar dhuAlHijja