test global variables
testDaysGlobalVariables

	self
		assert: YaumAlAhad = IslamicCalendar yaumAlAhad;
		assert: YaumAlIthnayna = IslamicCalendar yaumAlIthnayna;
		assert: YaumAthThalatha = IslamicCalendar yaumAthThalatha;
		assert: YaumAlArbaa = IslamicCalendar yaumAlArbaa;
		assert: YaumAlHamis = IslamicCalendar yaumAlHamis;
		assert: YaumAlJuma = IslamicCalendar yaumAlJuma;
		assert: YaumAsSabt = IslamicCalendar yaumAsSabt