test accessing
testDay

	self assert: (Rajab first, 1428) day = YaumAlIthnayna.
	self assert: (Rajab second, 1428) day = YaumAthThalatha.
	self assert: (Rajab third, 1428) day = YaumAlArbaa.
	self assert: (Rajab fourth, 1428) day = YaumAlHamis.
	self assert: (Rajab fifth, 1428) day = YaumAlJuma.
	self assert: (Rajab sixth, 1428) day = YaumAsSabt.
	self assert: (Rajab seventh, 1428) day = YaumAlAhad.
	self assert: (Rajab eighth, 1428) day = YaumAlIthnayna