test testing months
testIsIn

	self assert: (JulianJanuary seventh, 2007 isIn: JulianJanuary).
	self assert: (JulianFebruary seventh, 2007 isIn: JulianFebruary).
	self assert: (JulianMarch seventh, 2007 isIn: JulianMarch).
	self assert: (JulianApril seventh, 2007 isIn: JulianApril).
	self assert: (JulianMay seventh, 2007 isIn: JulianMay).
	self assert: (JulianJune seventh, 2007 isIn: JulianJune).
	self assert: (JulianJuly seventh, 2007 isIn: JulianJuly).
	self assert: (JulianAugust seventh, 2007 isIn: JulianAugust).
	self assert: (JulianSeptember seventh, 2007 isIn: JulianSeptember).
	self assert: (JulianOctober seventh, 2007 isIn: JulianOctober).
	self assert: (JulianNovember seventh, 2007 isIn: JulianNovember).
	self assert: (JulianDecember seventh, 2007 isIn: JulianDecember)