test global variables
testMonthsGlobalVariables

	self
		assert: JulianJanuary = JulianCalendar january;
		assert: JulianFebruary = JulianCalendar february;
		assert: JulianMarch = JulianCalendar march;
		assert: JulianApril = JulianCalendar april;
		assert: JulianMay = JulianCalendar may;
		assert: JulianJune = JulianCalendar june;
		assert: JulianJuly = JulianCalendar july;
		assert: JulianAugust = JulianCalendar august;
		assert: JulianSeptember = JulianCalendar september;
		assert: JulianOctober = JulianCalendar october;
		assert: JulianNovember = JulianCalendar november;
		assert: JulianDecember = JulianCalendar december