test testing months
testIsIn

	self assert: (Muharram first, 1428 isIn: Muharram).
	self assert: (Safar first, 1428 isIn: Safar).
	self assert: (RabiI first, 1428 isIn: RabiI).
	self assert: (RabiII first, 1428 isIn: RabiII).
	self assert: (JumadaI first, 1428 isIn: JumadaI).
	self assert: (JumadaII first, 1428 isIn: JumadaII).
	self assert: (Rajab first, 1428 isIn: Rajab).
	self assert: (Shaban first, 1428 isIn: Shaban).
	self assert: (Ramadan first, 1428 isIn: Ramadan).
	self assert: (Shawwal first, 1428 isIn: Shawwal).
	self assert: (DhuAlQada first, 1428 isIn: DhuAlQada).
	self assert: (DhuAlHijja first, 1428 isIn: DhuAlHijja)