test testing days
testIs

	self assert: (Ramadan ninth, 1428 is: YaumAlJuma).
	self assert: (Ramadan tenth, 1428 is: YaumAsSabt).
	self assert: (Ramadan eleventh, 1428 is: YaumAlAhad).
	self assert: (Ramadan twelfth, 1428 is: YaumAlIthnayna).
	self assert: (Ramadan thirteenth, 1428 is: YaumAthThalatha).
	self assert: (Ramadan fourteenth, 1428 is: YaumAlArbaa).
	self assert: (Ramadan fifteenth, 1428 is: YaumAlHamis)