initialization
initializeEpoch
	"The epoch or starting date is virtually never the date the calendar was adopted but rather a hypothetical starting point for the first day.
	The islamic calendar epoch is Muharram 1, 1 (R.D. 227015), that is equal to julian date Friday, July 16, 622 (gregorian date July 19, 622).
	- Extracted from 'Calendrical Calculations, The Millennium Edition'; page 88."

	epoch := 227015