initialization
initializeDaysGlobalVariables

	Smalltalk at: #YaumAlAhad put: self yaumAlAhad.
	Smalltalk at: #YaumAlIthnayna put: self yaumAlIthnayna.
	Smalltalk at: #YaumAthThalatha put: self yaumAthThalatha.
	Smalltalk at: #YaumAlArbaa put: self yaumAlArbaa.
	Smalltalk at: #YaumAlHamis put: self yaumAlHamis.
	Smalltalk at: #YaumAlJuma put: self yaumAlJuma.
	Smalltalk at: #YaumAsSabt put: self yaumAsSabt