test comparing
testHash

	self assert: yaumAlAhad hash = calendar yaumAlAhad hash.
	self assert: yaumAlIthnayna hash = calendar yaumAlIthnayna hash.
	self assert: yaumAthThalatha hash = calendar yaumAthThalatha hash.
	self assert: yaumAlArbaa hash = calendar yaumAlArbaa hash.
	self assert: yaumAlHamis hash = calendar yaumAlHamis hash.
	self assert: yaumAlJuma hash = calendar yaumAlJuma hash.
	self assert: yaumAsSabt hash = calendar yaumAsSabt hash 