test accessing
testNumberOfDaysInNonleapYear

	self assert: january numberOfDaysInNonleapYear = 31 daysMeasure.
	self assert: february numberOfDaysInNonleapYear = 28 daysMeasure.
	self assert: march numberOfDaysInNonleapYear = 31 daysMeasure.
	self assert: april numberOfDaysInNonleapYear = 30 daysMeasure.
	self assert: may numberOfDaysInNonleapYear = 31 daysMeasure.
	self assert: june numberOfDaysInNonleapYear = 30 daysMeasure.
	self assert: july numberOfDaysInNonleapYear = 31 daysMeasure.
	self assert: august numberOfDaysInNonleapYear = 31 daysMeasure.
	self assert: september numberOfDaysInNonleapYear = 30 daysMeasure.
	self assert: october numberOfDaysInNonleapYear = 31 daysMeasure.
	self assert: november numberOfDaysInNonleapYear = 30 daysMeasure.
	self assert: december numberOfDaysInNonleapYear = 31 daysMeasure