test testing
testIs

	self assert: (January is: january).
	self assert: (February is: february).
	self assert: (March is: march).
	self assert: (April is: april).
	self assert: (May is: may).
	self assert: (June is: june).
	self assert: (July is: july).
	self assert: (August is: august).
	self assert: (September is: september).
	self assert: (October is: october).
	self assert: (November is: november).
	self assert: (December is: december)