initialization
initializeMonthsGlobalVariables

	Smalltalk at: #Nisan put: self nisan.
	Smalltalk at: #Iyyar put: self iyyar.
	Smalltalk at: #Sivan put: self sivan.
	Smalltalk at: #Tammuz put: self tammuz.
	Smalltalk at: #Av put: self av.
	Smalltalk at: #Elul put: self elul.
	Smalltalk at: #Tishri put: self tishri.
	Smalltalk at: #Marheshvan put: self marheshvan.
	Smalltalk at: #Kislev put: self kislev.
	Smalltalk at: #Tevet put: self tevet.
	Smalltalk at: #Shevat put: self shevat.
	Smalltalk at: #Adar put: self adar.
	Smalltalk at: #AdarI put: self adarI.
	Smalltalk at: #AdarII put: self adarII