initialization
initializeEpoch
	"The epoch or starting date is virtually never the date the calendar was adopted but rather a hypothetical starting point for the first day.
	The hebrew calendar epoch is Tishri 1, 1 (R.D. -1373427), that is equal to julian date October 7, -3761 (gregorian date September 7, -3760).
	- Extracted from 'Calendrical Calculations, The Millennium Edition'; page 101."

	epoch := -1373427