test testing months
testIsIn

	self assert: (January seventh, 2007 isIn: January).
	self assert: (February seventh, 2007 isIn: February).
	self assert: (March seventh, 2007 isIn: March).
	self assert: (April seventh, 2007 isIn: April).
	self assert: (May seventh, 2007 isIn: May).
	self assert: (June seventh, 2007 isIn: June).
	self assert: (July seventh, 2007 isIn: July).
	self assert: (August seventh, 2007 isIn: August).
	self assert: (September seventh, 2007 isIn: September).
	self assert: (October seventh, 2007 isIn: October).
	self assert: (November seventh, 2007 isIn: November).
	self assert: (December seventh, 2007 isIn: December)