test accessing
testNumberOfDays
	self assert: january numberOfDays = 31 daysMeasure.
	self assert: february numberOfDays = 29 daysMeasure.
	self assert: march numberOfDays = 31 daysMeasure.
	self assert: april numberOfDays = 30 daysMeasure.
	self assert: may numberOfDays = 31 daysMeasure.
	self assert: june numberOfDays = 30 daysMeasure.
	self assert: july numberOfDays = 31 daysMeasure.
	self assert: august numberOfDays = 31 daysMeasure.
	self assert: september numberOfDays = 30 daysMeasure.
	self assert: october numberOfDays = 31 daysMeasure.
	self assert: november numberOfDays = 30 daysMeasure.
	self assert: december numberOfDays = 31 daysMeasure