test day of month creation
testDayOfMonthCreation

	self assert: january first = (DayOfMonth monthNumber: 1 dayNumber: 1 calendar: calendar).
	self assert: january second = (DayOfMonth monthNumber: 1 dayNumber: 2 calendar: calendar).
	self assert: january third = (DayOfMonth monthNumber: 1 dayNumber: 3 calendar: calendar).
	self assert: january fourth = (DayOfMonth monthNumber: 1 dayNumber: 4 calendar: calendar).
	self assert: january fifth = (DayOfMonth monthNumber: 1 dayNumber: 5 calendar: calendar).
	self assert: january sixth = (DayOfMonth monthNumber: 1 dayNumber: 6 calendar: calendar).
	self assert: january seventh = (DayOfMonth monthNumber: 1 dayNumber: 7 calendar: calendar).
	self assert: january eighth = (DayOfMonth monthNumber: 1 dayNumber: 8 calendar: calendar).
	self assert: january ninth = (DayOfMonth monthNumber: 1 dayNumber: 9 calendar: calendar).
	self assert: january tenth = (DayOfMonth monthNumber: 1 dayNumber: 10 calendar: calendar).
	self assert: january eleventh = (DayOfMonth monthNumber: 1 dayNumber: 11 calendar: calendar).
	self assert: january twelfth = (DayOfMonth monthNumber: 1 dayNumber: 12 calendar: calendar).
	self assert: january thirteenth = (DayOfMonth monthNumber: 1 dayNumber: 13 calendar: calendar).
	self assert: january fourteenth = (DayOfMonth monthNumber: 1 dayNumber: 14 calendar: calendar).
	self assert: january fifteenth = (DayOfMonth monthNumber: 1 dayNumber: 15 calendar: calendar).
	self assert: january sixteenth = (DayOfMonth monthNumber: 1 dayNumber: 16 calendar: calendar).
	self assert: january seventeenth = (DayOfMonth monthNumber: 1 dayNumber: 17 calendar: calendar).
	self assert: january eighteenth = (DayOfMonth monthNumber: 1 dayNumber: 18 calendar: calendar).
	self assert: january nineteenth = (DayOfMonth monthNumber: 1 dayNumber: 19 calendar: calendar).
	self assert: january twentieth = (DayOfMonth monthNumber: 1 dayNumber: 20 calendar: calendar).
	self assert: january twentyfirst = (DayOfMonth monthNumber: 1 dayNumber: 21 calendar: calendar).
	self assert: january twentysecond = (DayOfMonth monthNumber: 1 dayNumber: 22 calendar: calendar).
	self assert: january twentythird = (DayOfMonth monthNumber: 1 dayNumber: 23 calendar: calendar).
	self assert: january twentyfourth = (DayOfMonth monthNumber: 1 dayNumber: 24 calendar: calendar).
	self assert: january twentyfifth = (DayOfMonth monthNumber: 1 dayNumber: 25 calendar: calendar).
	self assert: january twentysixth = (DayOfMonth monthNumber: 1 dayNumber: 26 calendar: calendar).
	self assert: january twentyseventh = (DayOfMonth monthNumber: 1 dayNumber: 27 calendar: calendar).
	self assert: january twentyeighth = (DayOfMonth monthNumber: 1 dayNumber: 28 calendar: calendar).
	self assert: january twentyninth = (DayOfMonth monthNumber: 1 dayNumber: 29 calendar: calendar)