test accessing
testFirstDayOfMonth

	self assert: january firstDayOfMonth = January first.
	self assert: february firstDayOfMonth = February first.
	self assert: march firstDayOfMonth = March first.
	self assert: april firstDayOfMonth = April first.
	self assert: may firstDayOfMonth = May first.
	self assert: june firstDayOfMonth = June first.
	self assert: july firstDayOfMonth = July first.
	self assert: august firstDayOfMonth = August first.
	self assert: september firstDayOfMonth = September first.
	self assert: october firstDayOfMonth = October first.
	self assert: november firstDayOfMonth = November first.
	self assert: december firstDayOfMonth = December first