test accessing
testNumberOfDaysInLeapYear

	self assert: january numberOfDaysInLeapYear = 31 daysMeasure.
	self assert: february numberOfDaysInLeapYear = 29 daysMeasure.
	self assert: march numberOfDaysInLeapYear = 31 daysMeasure.
	self assert: april numberOfDaysInLeapYear = 30 daysMeasure.
	self assert: may numberOfDaysInLeapYear = 31 daysMeasure.
	self assert: june numberOfDaysInLeapYear = 30 daysMeasure.
	self assert: july numberOfDaysInLeapYear = 31 daysMeasure.
	self assert: august numberOfDaysInLeapYear = 31 daysMeasure.
	self assert: september numberOfDaysInLeapYear = 30 daysMeasure.
	self assert: october numberOfDaysInLeapYear = 31 daysMeasure.
	self assert: november numberOfDaysInLeapYear = 30 daysMeasure.
	self assert: december numberOfDaysInLeapYear = 31 daysMeasure