test printing
testPrintString

	self assert: january printString = 'January'.
	self assert: february printString = 'February'.
	self assert: march printString = 'March'.
	self assert: april printString = 'April'.
	self assert: may printString = 'May'.
	self assert: june printString = 'June'.
	self assert: july printString = 'July'.
	self assert: august printString = 'August'.
	self assert: september printString = 'September'.
	self assert: october printString = 'October'.
	self assert: november printString = 'November'.
	self assert: december printString = 'December'