test comparing
testHash

	self assert: yomRishon hash = calendar yomRishon hash.
	self assert: yomSheni hash = calendar yomSheni hash.
	self assert: yomShelishi hash = calendar yomShelishi hash.
	self assert: yomRevii hash = calendar yomRevii hash.
	self assert: yomHamishi hash = calendar yomHamishi hash.
	self assert: yomShishi hash = calendar yomShishi hash.
	self assert: yomShabbat hash = calendar yomShabbat hash