SystemOrganization addCategory: #'Chalten-Tests'!
SystemOrganization addCategory: 'Chalten-Tests-FilterModel'!
SystemOrganization addCategory: 'Chalten-Tests-GregorianModel'!
SystemOrganization addCategory: 'Chalten-Tests-HebrewModel'!
SystemOrganization addCategory: 'Chalten-Tests-IslamicModel'!
SystemOrganization addCategory: 'Chalten-Tests-JulianModel'!
SystemOrganization addCategory: 'Chalten-Tests-RomanModel'!
SystemOrganization addCategory: 'Chalten-Tests-TimeModel'!
