initialization
setUp
	calendar := IslamicCalendar.
	muharram := calendar muharram.
	safar := calendar safar.
	rabiI := calendar rabiI.
	rabiII := calendar rabiII.
	jumadaI := calendar jumadaI.
	jumadaII := calendar jumadaII.
	rajab := calendar rajab.
	shaban := calendar shaban.
	ramadan := calendar ramadan.
	shawwal := calendar shawwal.
	dhuAlQada := calendar dhuAlQada.
	dhuAlHijja := calendar dhuAlHijja.
	zeroMonths := 0 monthsMeasure.
	oneMonth := 1 monthMeasure.
	twoMonths := 2 monthsMeasure.
	elevenMonths := 11 monthsMeasure.
	twelveMonths := 12 monthsMeasure