test comparing
testEqual

	self assert: muharram = muharram.
	self assert: safar = safar.
	self assert: rabiI = rabiI.
	self assert: rabiII = rabiII.
	self assert: jumadaI = jumadaI.
	self assert: jumadaII = jumadaII.
	self assert: rajab = rajab.
	self assert: shaban = shaban.
	self assert: ramadan = ramadan.
	self assert: shawwal = shawwal.
	self assert: dhuAlQada = dhuAlQada.
	self assert: dhuAlHijja = dhuAlHijja