test accessing
testNumberOfDays
	self assert: muharram numberOfDays = 30 daysMeasure.
	self assert: safar numberOfDays = 29 daysMeasure.
	self assert: rabiI numberOfDays = 30 daysMeasure.
	self assert: rabiII numberOfDays = 29 daysMeasure.
	self assert: jumadaI numberOfDays = 30 daysMeasure.
	self assert: jumadaII numberOfDays = 29 daysMeasure.
	self assert: rajab numberOfDays = 30 daysMeasure.
	self assert: shaban numberOfDays = 29 daysMeasure.
	self assert: ramadan numberOfDays = 30 daysMeasure.
	self assert: shawwal numberOfDays = 29 daysMeasure.
	self assert: dhuAlQada numberOfDays = 30 daysMeasure.
	self assert: dhuAlHijja numberOfDays = 30 daysMeasure