test accessing
testLastDayOfMonth

	self assert: muharram lastDayOfMonth = Muharram thirtieth.
	self assert: safar lastDayOfMonth = Safar twentyninth.
	self assert: rabiI lastDayOfMonth = RabiI thirtieth.
	self assert: rabiII lastDayOfMonth = RabiII twentyninth.
	self assert: jumadaI lastDayOfMonth = JumadaI thirtieth.
	self assert: jumadaII lastDayOfMonth = JumadaII twentyninth.
	self assert: rajab lastDayOfMonth = Rajab thirtieth.
	self assert: shaban lastDayOfMonth = Shaban twentyninth.
	self assert: ramadan lastDayOfMonth = Ramadan thirtieth.
	self assert: shawwal lastDayOfMonth = Shawwal twentyninth.
	self assert: dhuAlQada lastDayOfMonth = DhuAlQada thirtieth.
	self assert: dhuAlHijja lastDayOfMonth = DhuAlHijja thirtieth