test day of month creation
testDayOfMonthCreation

	self assert: ramadan first = (DayOfMonth monthNumber: 9 dayNumber: 1 calendar: calendar).
	self assert: ramadan second = (DayOfMonth monthNumber: 9 dayNumber: 2 calendar: calendar).
	self assert: ramadan third = (DayOfMonth monthNumber: 9 dayNumber: 3 calendar: calendar).
	self assert: ramadan fourth = (DayOfMonth monthNumber: 9 dayNumber: 4 calendar: calendar).
	self assert: ramadan fifth = (DayOfMonth monthNumber: 9 dayNumber: 5 calendar: calendar).
	self assert: ramadan sixth = (DayOfMonth monthNumber: 9 dayNumber: 6 calendar: calendar).
	self assert: ramadan seventh = (DayOfMonth monthNumber: 9 dayNumber: 7 calendar: calendar).
	self assert: ramadan eighth = (DayOfMonth monthNumber: 9 dayNumber: 8 calendar: calendar).
	self assert: ramadan ninth = (DayOfMonth monthNumber: 9 dayNumber: 9 calendar: calendar).
	self assert: ramadan tenth = (DayOfMonth monthNumber: 9 dayNumber: 10 calendar: calendar).
	self assert: ramadan eleventh = (DayOfMonth monthNumber: 9 dayNumber: 11 calendar: calendar).
	self assert: ramadan twelfth = (DayOfMonth monthNumber: 9 dayNumber: 12 calendar: calendar).
	self assert: ramadan thirteenth = (DayOfMonth monthNumber: 9 dayNumber: 13 calendar: calendar).
	self assert: ramadan fourteenth = (DayOfMonth monthNumber: 9 dayNumber: 14 calendar: calendar).
	self assert: ramadan fifteenth = (DayOfMonth monthNumber: 9 dayNumber: 15 calendar: calendar).
	self assert: ramadan sixteenth = (DayOfMonth monthNumber: 9 dayNumber: 16 calendar: calendar).
	self assert: ramadan seventeenth = (DayOfMonth monthNumber: 9 dayNumber: 17 calendar: calendar).
	self assert: ramadan eighteenth = (DayOfMonth monthNumber: 9 dayNumber: 18 calendar: calendar).
	self assert: ramadan nineteenth = (DayOfMonth monthNumber: 9 dayNumber: 19 calendar: calendar).
	self assert: ramadan twentieth = (DayOfMonth monthNumber: 9 dayNumber: 20 calendar: calendar).
	self assert: ramadan twentyfirst = (DayOfMonth monthNumber: 9 dayNumber: 21 calendar: calendar).
	self assert: ramadan twentysecond = (DayOfMonth monthNumber: 9 dayNumber: 22 calendar: calendar).
	self assert: ramadan twentythird = (DayOfMonth monthNumber: 9 dayNumber: 23 calendar: calendar).
	self assert: ramadan twentyfourth = (DayOfMonth monthNumber: 9 dayNumber: 24 calendar: calendar).
	self assert: ramadan twentyfifth = (DayOfMonth monthNumber: 9 dayNumber: 25 calendar: calendar).
	self assert: ramadan twentysixth = (DayOfMonth monthNumber: 9 dayNumber: 26 calendar: calendar).
	self assert: ramadan twentyseventh = (DayOfMonth monthNumber: 9 dayNumber: 27 calendar: calendar).
	self assert: ramadan twentyeighth = (DayOfMonth monthNumber: 9 dayNumber: 28 calendar: calendar).
	self assert: ramadan twentyninth = (DayOfMonth monthNumber: 9 dayNumber: 29 calendar: calendar).
	self assert: ramadan thirtieth = (DayOfMonth monthNumber: 9 dayNumber: 30 calendar: calendar)