test accessing
testFirstDayOfMonth

	self assert: muharram firstDayOfMonth = Muharram first.
	self assert: safar firstDayOfMonth = Safar first.
	self assert: rabiI firstDayOfMonth = RabiI first.
	self assert: rabiII firstDayOfMonth = RabiII first.
	self assert: jumadaI firstDayOfMonth = JumadaI first.
	self assert: jumadaII firstDayOfMonth = JumadaII first.
	self assert: rajab firstDayOfMonth = Rajab first.
	self assert: shaban firstDayOfMonth = Shaban first.
	self assert: ramadan firstDayOfMonth = Ramadan first.
	self assert: shawwal firstDayOfMonth = Shawwal first.
	self assert: dhuAlQada firstDayOfMonth = DhuAlQada first.
	self assert: dhuAlHijja firstDayOfMonth = DhuAlHijja first