initialization
initializeMonthsGlobalVariables

	Smalltalk at: #Muharram put: self muharram.
	Smalltalk at: #Safar put: self safar.
	Smalltalk at: #RabiI put: self rabiI.
	Smalltalk at: #RabiII put: self rabiII.
	Smalltalk at: #JumadaI put: self jumadaI.
	Smalltalk at: #JumadaII put: self jumadaII.
	Smalltalk at: #Rajab put: self rajab.
	Smalltalk at: #Shaban put: self shaban.
	Smalltalk at: #Ramadan put: self ramadan.
	Smalltalk at: #Shawwal put: self shawwal.
	Smalltalk at: #DhuAlQada put: self dhuAlQada.
	Smalltalk at: #DhuAlHijja put: self dhuAlHijja