test testing days
testIs

	self assert: (September ninth, 2007 is: Sunday).
	self assert: (September tenth, 2007 is: Monday).
	self assert: (September eleventh, 2007 is: Tuesday).
	self assert: (September twelfth, 2007 is: Wednesday).
	self assert: (September thirteenth, 2007 is: Thursday).
	self assert: (September fourteenth, 2007 is: Friday).
	self assert: (September fifteenth, 2007 is: Saturday)