initialization
setUp
	calendar := HebrewCalendar.
	yomRishon := calendar yomRishon.
	yomSheni := calendar yomSheni.
	yomShelishi := calendar yomShelishi.
	yomRevii := calendar yomRevii.
	yomHamishi := calendar yomHamishi.
	yomShishi := calendar yomShishi.
	yomShabbat := calendar yomShabbat.
	zeroDays := 0 daysMeasure.
	oneDay := 1 dayMeasure.
	twoDays := 2 daysMeasure.
	sevenDays := 7 daysMeasure.
	minusOneDay := -1 dayMeasure