test comparing
testHash

	self assert: january hash = january hash.
	self assert: february hash = february hash.
	self assert: march hash = march hash.
	self assert: april hash = april hash.
	self assert: may hash = may hash.
	self assert: june hash = june hash.
	self assert: july hash = july hash.
	self assert: august hash = august hash.
	self assert: september hash = september hash.
	self assert: october hash = october hash.
	self assert: november hash = november hash.
	self assert: december hash = december hash