test testing
testIs

	self assert: (JulianJanuary is: january).
	self assert: (JulianFebruary is: february).
	self assert: (JulianMarch is: march).
	self assert: (JulianApril is: april).
	self assert: (JulianMay is: may).
	self assert: (JulianJune is: june).
	self assert: (JulianJuly is: july).
	self assert: (JulianAugust is: august).
	self assert: (JulianSeptember is: september).
	self assert: (JulianOctober is: october).
	self assert: (JulianNovember is: november).
	self assert: (JulianDecember is: december)