test accessing
testNumberOfDays
	self assert: 5761 asHebrewYear numberOfDays = 353 daysMeasure.
	self assert: 5762 asHebrewYear numberOfDays = 354 daysMeasure.
	self assert: 5763 asHebrewYear numberOfDays = 385 daysMeasure.
	self assert: 5764 asHebrewYear numberOfDays = 355 daysMeasure.
	self assert: 5765 asHebrewYear numberOfDays = 383 daysMeasure.
	self assert: 5766 asHebrewYear numberOfDays = 354 daysMeasure.
	self assert: 5767 asHebrewYear numberOfDays = 355 daysMeasure.
	self assert: 5768 asHebrewYear numberOfDays = 383 daysMeasure.
	self assert: 5769 asHebrewYear numberOfDays = 354 daysMeasure.
	self assert: 5770 asHebrewYear numberOfDays = 355 daysMeasure.
	self assert: 5771 asHebrewYear numberOfDays = 385 daysMeasure.
	self assert: 5772 asHebrewYear numberOfDays = 354 daysMeasure.
	self assert: 5773 asHebrewYear numberOfDays = 353 daysMeasure.
	self assert: 5774 asHebrewYear numberOfDays = 385 daysMeasure.
	self assert: 5775 asHebrewYear numberOfDays = 354 daysMeasure.
	self assert: 5776 asHebrewYear numberOfDays = 385 daysMeasure.
	self assert: 5777 asHebrewYear numberOfDays = 353 daysMeasure.
	self assert: 5778 asHebrewYear numberOfDays = 354 daysMeasure.
	self assert: 5779 asHebrewYear numberOfDays = 385 daysMeasure.
	self assert: 5780 asHebrewYear numberOfDays = 355 daysMeasure.
	self assert: 5781 asHebrewYear numberOfDays = 353 daysMeasure.
	self assert: 5782 asHebrewYear numberOfDays = 384 daysMeasure