initialization
initializeMonthsGlobalVariables

	Smalltalk at: #JulianJanuary put: self january.
	Smalltalk at: #JulianFebruary put: self february.
	Smalltalk at: #JulianMarch put: self march.
	Smalltalk at: #JulianApril put: self april.
	Smalltalk at: #JulianMay put: self may.
	Smalltalk at: #JulianJune put: self june.
	Smalltalk at: #JulianJuly put: self july.
	Smalltalk at: #JulianAugust put: self august.
	Smalltalk at: #JulianSeptember put: self september.
	Smalltalk at: #JulianOctober put: self october.
	Smalltalk at: #JulianNovember put: self november.
	Smalltalk at: #JulianDecember put: self december