initialization
setUp
	calendar := IslamicCalendar.
	yaumAlAhad := calendar yaumAlAhad.
	yaumAlIthnayna := calendar yaumAlIthnayna.
	yaumAthThalatha := calendar yaumAthThalatha.
	yaumAlArbaa := calendar yaumAlArbaa.
	yaumAlHamis := calendar yaumAlHamis.
	yaumAlJuma := calendar yaumAlJuma.
	yaumAsSabt := calendar yaumAsSabt.
	zeroDays := 0 daysMeasure.
	oneDay := 1 dayMeasure.
	twoDays := 2 daysMeasure.
	sevenDays := 7 daysMeasure.
	minusOneDay := -1 dayMeasure