initialization
initializeMonths

	self addMonth: self createJanuary.
	self addMonth: self createFebruary.
	self addMonth: self createMarch.
	self addMonth: self createApril.
	self addMonth: self createMay.
	self addMonth: self createJune.
	self addMonth: self createJuly.
	self addMonth: self createAugust.
	self addMonth: self createSeptember.
	self addMonth: self createOctober.
	self addMonth: self createNovember.
	self addMonth: self createDecember