test comparing
testHash

	self assert: muharram hash = muharram hash.
	self assert: safar hash = safar hash.
	self assert: rabiI hash = rabiI hash.
	self assert: rabiII hash = rabiII hash.
	self assert: jumadaI hash = jumadaI hash.
	self assert: jumadaII hash = jumadaII hash.
	self assert: rajab hash = rajab hash.
	self assert: shaban hash = shaban hash.
	self assert: ramadan hash = ramadan hash.
	self assert: shawwal hash = shawwal hash.
	self assert: dhuAlQada hash = dhuAlQada hash.
	self assert: dhuAlHijja hash = dhuAlHijja hash