test testing
testIs

	self assert: (Muharram is: muharram).
	self assert: (Safar is: safar).
	self assert: (RabiI is: rabiI).
	self assert: (RabiII is: rabiII).
	self assert: (JumadaI is: jumadaI).
	self assert: (JumadaII is: jumadaII).
	self assert: (Rajab is: rajab).
	self assert: (Shaban is: shaban).
	self assert: (Ramadan is: ramadan).
	self assert: (Shawwal is: shawwal).
	self assert: (DhuAlQada is: dhuAlQada).
	self assert: (DhuAlHijja is: dhuAlHijja)