test accessing
testLastDayNumber

	self assert: muharram lastDayNumber = 30.
	self assert: safar lastDayNumber = 29.
	self assert: rabiI lastDayNumber = 30.
	self assert: rabiII lastDayNumber = 29.
	self assert: jumadaI lastDayNumber = 30.
	self assert: jumadaII lastDayNumber = 29.
	self assert: rajab lastDayNumber = 30.
	self assert: shaban lastDayNumber = 29.
	self assert: ramadan lastDayNumber = 30.
	self assert: shawwal lastDayNumber = 29.
	self assert: dhuAlQada lastDayNumber = 30.
	self assert: dhuAlHijja lastDayNumber = 30